# Generated by Django 5.2.17 on 2026-10-02 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('product_slug', models.CharField(db_index=True, max_length=255)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', 'chunk_index'], name='ai_search_b_product_1b8244_idx')],
                'unique_together': {('product_id', 'chunk_index')},
            },
        ),
    ]
