# Generated by Django 5.2.17 on 2026-10-02 02:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRMSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('key_nonce', models.BinaryField(max_length=12)),
                ('key_ciphertext', models.BinaryField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['user_email', 'product_id'], name='drm_drmsess_user_em_f825b7_idx'), models.Index(fields=['expires_at'], name='drm_drmsess_expires_efcd73_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('completion_percent', models.FloatField(default=0.0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_email', 'product_id')},
            },
        ),
    ]
